import { GameDef } from '../../core/types/GameDef';
import { WinMode } from '../../core/types/WinMode';
import FontUtils from '../../core/utils/FontUtils';
import PathUtils from '../../core/utils/PathUtils';

/**
 * This is the definition for the Great Western Trail game.
 * @author cophilot
 * @version 1.0.0
 * @created 2026-6-5
 */
export default function getDefinition(): GameDef {
	const gameTitle = 'Great Western Trail';
	const pu = new PathUtils(gameTitle);

	return {
		title: gameTitle,
		banner:
			'https://wallpapers.com/images/hd/old-town-western-aesthetic-87otv3nnofq978zj.jpg',
		url: 'https://boardgamegeek.com/boardgame/341169/great-western-trail-second-edition',
		rulesUrl:
			'https://www.brettspielversand.de/mediafiles/spieleanleitungen/eggert/13-0048_GreatWesternTrail_2Edition_Anleitung.pdf?srsltid=AfmBOoq86-ZT0Fr_ZDcDyiBxko1QYTk_1kttB64llJwKlh7c6BMNXtSO',
		bgColor: '#fcfcd9',
		fontColor: '#242121',
		primaryColor: '#171c22',
		secondaryColor: '#ee521a',
		fontFamily: FontUtils.getClassicFont(),
		playerSizes: [1, 2, 3, 4],
		winMode: WinMode.MOST,
		rows: [
			{
				name: 'Leftover Dollars',
				description: 'Gain 1 victory point for every 5 Dollars that you own.',
				icon: pu.getAbsoluteImagePath('rest-dollar'),
			},
			{
				name: 'Buildings',
				description:
					'Gain the sum of the victory points printed on each of your private building tiles that is placed on the game board.',
				icon: pu.getAbsoluteImagePath('building'),
			},
			{
				name: 'City Crests',
				description:
					'Gain points the that sum you of have the victory unlocked with your discs on the city crests. Any negative victory points must be subtracted of course.',
				icon: pu.getAbsoluteImagePath('cities'),
			},
			{
				name: 'Train Stations',
				description:
					'Gain the sum of the victory points printed right next to each train station that has your disc on it.',
				icon: pu.getAbsoluteImagePath('train-station'),
			},
			{
				name: 'Hazard Tiles',
				description:
					'Gain the sum of the victory points printed on each of the collected hazard tiles in front of you.',
				icon: pu.getAbsoluteImagePath('hazard-tile'),
			},
			{
				name: 'Cattle Cards',
				description:
					'From your deck (personal draw stack, hand cards and personal discard pile), seek out all cattle cards that have victory points on them. Then gain the sum of those victory points.',
				icon: pu.getAbsoluteImagePath('cattle-cards'),
			},
			{
				name: 'Objective Cards',
				description:
					'You must seek out all objective cards that you still have in your deck. For each of those, you must decide whether you want to remove it from the game or add it to your personal objective area now (without using its immediate action). Afterwards, check each objective card in your personal objective area to see if you have fulfilled each of its tasks individually. For all cards that are entirely fulfilled, sum the positive victory points printed on them. For all cards that you have not fulfilled completely, subtract the negative points printed on them.',
				icon: pu.getAbsoluteImagePath('objective-card'),
			},
			{
				name: 'Individual Tasks',
				description:
					'Gain the sum of victory points generated by the individual tasks of the station master tiles that you have in front of you.',
				icon: pu.getAbsoluteImagePath('individual-tasks'),
			},
			{
				name: 'Workers',
				description:
					'Gain 4 victory points for each worker that is placed on the fifth or sixth space of any row in your worker section.',
				icon: pu.getAbsoluteImagePath('workers'),
			},
			{
				name: 'Player Board Space',
				description:
					'Gain 3 victory points if you managed to clear this disc space on your player board.',
				icon: pu.getAbsoluteImagePath('player-board'),
				checkValue: 3,
			},
			{
				name: 'Job Market Token',
				description:
					'Gain 2 victory points if you have the job market token in front of you.',
				icon: pu.getAbsoluteImagePath('job-market-token'),
				checkValue: 2,
			},
		],
	};
}
